// <auto-generated />
namespace SklepInternetowyAK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_addDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_addDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202104131202595_add_addDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
